---
title: Bacaan Seru
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Bacaan Seru
description: Semua Bacaan Seru hanya di bacaanseru.com
logo: assets/images/logo.png
favicon: assets/images/logo.png
baseurl: ''
google_analytics: UA-108020977-3
disqus: bacaanseru
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
- _pages
permalink: "/:title/"
authors:
  Danz:
    name: Danz
    display_name: Danz
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: selaluberita24@gmail.com
    web: https://www.bacaanseru.com
    twitter: https://instagram.com/bacaanseru2020
    description: Belajar Belajar dan Belajar, hidup itu belajar, belajar memaknai
      belajar memahami
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
paginate: 6
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: enabled
adsense-data-ad-client: ca-pub-3357859106517463
adsense-data-ad-slot: '1075173409'
lazyimages: disabled
exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
